export const routes = {
  AUTH_NAVIGATOR: 'AuthNavigator',
  TAB_NAVIGATOR: 'TabNavigator',
  OTHER_NAVIGATOR: 'OtherNavigator',
  HOME: 'Home',
  CATEGORIES: 'Categories',
  PRODUCTS: 'Products',
  PRODUCT_DETAIL: 'ProductDetail',
  BASKET: 'Basket',
  NOTIFICATION: 'Notification',
  ORDERS: 'Orders',
  ORDER_DETAIL:'OrderDetail',
  PROFILE: 'Profile',
  SPLASH_SCREEN: 'SplashScreen',
  LOGIN: 'Login',
  REGISTER: 'Register',
  FORGOT_PASSWORD: 'ForgotPassword',
  HOME: 'Home',
  NOTIFICATION: 'Notification',
  PROFILE: 'Profile',
  EMAIl_SEND: 'EmailSend',
  ADDRESS:'Address',
  PAYMENT:'Payment',
  WISHLIST:'Wishlist',
  ADD_ADDRESS:'AddAddress',
  ADD_PAYMENT:'AddPayment',
  FAVORITES:'Favorites',
  CHECKOUT:'CheckOut',
  ORDER_PLACED:'OrderPlaced'
};

export default routes;
